char_False --> char_F,char_alse.
char_alse --> char_a,char_lse.
char_lse --> char_l,char_se.
char_se --> char_s,char_e.
char_class --> char_c,char_lass.
char_lass --> char_l,char_ass.
char_ass --> char_a,char_ss.
char_ss --> char_s,char_s.
char_finally --> char_f,char_inally.
char_inally --> char_i,char_nally.
char_nally --> char_n,char_ally.
char_ally --> char_a,char_lly.
char_lly --> char_l,char_ly.
char_ly --> char_l,char_y.
char_is --> char_i,char_s.
char_return --> char_r,char_eturn.
char_eturn --> char_e,char_turn.
char_turn --> char_t,char_urn.
char_urn --> char_u,char_rn.
char_rn --> char_r,char_n.
char_None --> char_N,char_one.
char_one --> char_o,char_ne.
char_ne --> char_n,char_e.
char_continue --> char_c,char_ontinue.
char_ontinue --> char_o,char_ntinue.
char_ntinue --> char_n,char_tinue.
char_tinue --> char_t,char_inue.
char_inue --> char_i,char_nue.
char_nue --> char_n,char_ue.
char_ue --> char_u,char_e.
char_for --> char_f,char_or.
char_or --> char_o,char_r.
char_lambda --> char_l,char_ambda.
char_ambda --> char_a,char_mbda.
char_mbda --> char_m,char_bda.
char_bda --> char_b,char_da.
char_da --> char_d,char_a.
char_try --> char_t,char_ry.
char_ry --> char_r,char_y.
char_True --> char_T,char_rue.
char_rue --> char_r,char_ue.
char_def --> char_d,char_ef.
char_ef --> char_e,char_f.
char_from --> char_f,char_rom.
char_rom --> char_r,char_om.
char_om --> char_o,char_m.
char_nonlocal --> char_n,char_onlocal.
char_onlocal --> char_o,char_nlocal.
char_nlocal --> char_n,char_local.
char_local --> char_l,char_ocal.
char_ocal --> char_o,char_cal.
char_cal --> char_c,char_al.
char_al --> char_a,char_l.
char_while --> char_w,char_hile.
char_hile --> char_h,char_ile.
char_ile --> char_i,char_le.
char_le --> char_l,char_e.
char_and --> char_a,char_nd.
char_nd --> char_n,char_d.
char_del --> char_d,char_el.
char_el --> char_e,char_l.
char_global --> char_g,char_lobal.
char_lobal --> char_l,char_obal.
char_obal --> char_o,char_bal.
char_bal --> char_b,char_al.
char_not --> char_n,char_ot.
char_ot --> char_o,char_t.
char_with --> char_w,char_ith.
char_ith --> char_i,char_th.
char_th --> char_t,char_h.
char_as --> char_a,char_s.
char_elif --> char_e,char_lif.
char_lif --> char_l,char_if.
char_if --> char_i,char_f.
char_yield --> char_y,char_ield.
char_ield --> char_i,char_eld.
char_eld --> char_e,char_ld.
char_ld --> char_l,char_d.
char_assert --> char_a,char_ssert.
char_ssert --> char_s,char_sert.
char_sert --> char_s,char_ert.
char_ert --> char_e,char_rt.
char_rt --> char_r,char_t.
char_else --> char_e,char_lse.
char_import --> char_i,char_mport.
char_mport --> char_m,char_port.
char_port --> char_p,char_ort.
char_ort --> char_o,char_rt.
char_pass --> char_p,char_ass.
char_break --> char_b,char_reak.
char_reak --> char_r,char_eak.
char_eak --> char_e,char_ak.
char_ak --> char_a,char_k.
char_except --> char_e,char_xcept.
char_xcept --> char_x,char_cept.
char_cept --> char_c,char_ept.
char_ept --> char_e,char_pt.
char_pt --> char_p,char_t.
char_in --> char_i,char_n.
char_raise --> char_r,char_aise.
char_aise --> char_a,char_ise.
char_ise --> char_i,char_se.
char_not96in --> char_n,char_ot96in.
char_ot96in --> char_o,char_t96in.
char_t96in --> char_t,char_96in.
char_96in --> char_96,char_in.
char_is96not --> char_i,char_s96not.
char_s96not --> char_s,char_96not.
char_96not --> char_96,char_not.
char_6060 --> char_60,char_60.
char_4361 --> char_43,char_61.
char_4561 --> char_45,char_61.
char_4261 --> char_42,char_61.
char_474761 --> char_47,char_4761.
char_4761 --> char_47,char_61.
char_3761 --> char_37,char_61.
char_424261 --> char_42,char_4261.
char_606061 --> char_60,char_6061.
char_626261 --> char_62,char_6261.
char_6161 --> char_61,char_61.
char_3361 --> char_33,char_61.
char_6261 --> char_62,char_61.
char_6061 --> char_60,char_61.
char_4242 --> char_42, char_42.
char_4747 --> char_47, char_47.
char_6262 --> char_62, char_62.
char_32 --> " ".
char_33 --> "!".
char_34 --> "\"".
char_35 --> "#".
char_36 --> "$".
char_37 --> "%".
char_38 --> "&".
char_39 --> "'".
char_40 --> "(".
char_41 --> ")".
char_42 --> "*".
char_43 --> "+".
char_44 --> ",".
char_45 --> "-".
char_46 --> ".".
char_47 --> "/".
char_0 --> "0".
char_1 --> "1".
char_2 --> "2".
char_3 --> "3".
char_4 --> "4".
char_5 --> "5".
char_6 --> "6".
char_7 --> "7".
char_8 --> "8".
char_9 --> "9".
char_10 --> "\n".
char_58 --> ":".
char_59 --> ";".
char_60 --> "<".
char_61 --> "=".
char_62 --> ">".
char_63 --> "?".
char_64 --> "@".
char_A --> "A".
char_B --> "B".
char_C --> "C".
char_D --> "D".
char_E --> "E".
char_F --> "F".
char_G --> "G".
char_H --> "H".
char_I --> "I".
char_J --> "J".
char_K --> "K".
char_L --> "L".
char_M --> "M".
char_N --> "N".
char_O --> "O".
char_P --> "P".
char_Q --> "Q".
char_R --> "R".
char_S --> "S".
char_T --> "T".
char_U --> "U".
char_V --> "V".
char_W --> "W".
char_X --> "X".
char_Y --> "Y".
char_Z --> "Z".
char_91 --> "[".
char_92 --> "\\".
char_93 --> "]".
char_94 --> "^".
char_95 --> "_".
char_96 --> "`".
char_a --> "a".
char_b --> "b".
char_c --> "c".
char_d --> "d".
char_e --> "e".
char_f --> "f".
char_g --> "g".
char_h --> "h".
char_i --> "i".
char_j --> "j".
char_k --> "k".
char_l --> "l".
char_m --> "m".
char_n --> "n".
char_o --> "o".
char_p --> "p".
char_q --> "q".
char_r --> "r".
char_s --> "s".
char_t --> "t".
char_u --> "u".
char_v --> "v".
char_w --> "w".
char_x --> "x".
char_y --> "y".
char_z --> "z".
char_123 --> "{".
char_124 --> "|".
char_125 --> "}".
char_126 --> "~".
char_tab --> "\t".